### ISSUE TITLE
Chuncksize in performance.pmap implemented differently than documented

### ISSUE THREAD

**Issue by HenniOVP** [HDembinski/pyik#2]
Hi,

the function performance.pmap takes the optional argument chunksize.
However in the source code this is not implemented as the size of the chunks for each porcess but as the number of chunks that are distributed.

Cheers,
Hendrik

**Comment by HenniOVP** [comment]
Hi,

I just wanted to start working on this issue and a question came up: How should the variable behave in the future?

Should the variable `chunksize` be implemented as what chunksize implies, i.e. how big each chunk is or should `chunksize` just be renamed to something like `number_chunks` and thus match the current implementation? Or would such a change in API the just be a really bad idea?
Another approach would be to just change the doc string to precisely describe the current implementation, while keeping `chunksize` as the variable name. Then the variable name is still somewhat ambiguous, but the documentation matches the implementation, which is most important in my opinion.

**Comment by HDembinski** [comment]
Minimal fix is to make the documentation correct.
Since pyik is not widely used, we can still change the implementation when it is wrong.
So what do you think would be the best behavior?

**Comment by HDembinski** [comment]
We can also do it in a backward compatible way. We can add a new keyword called `nchunks`, which is a better name for what this variable is actually doing, and raise a deprecation warning every time the old `chunksize` keyword is used, but it would have the same effect as `nchunks`. This way, we get a softer transition.

**Comment by HDembinski** [comment]
I would not put a lot of effort into `pmap`, it is likely superseded by other tools by now, like numexpr, numba, and so on.

**Comment by HenniOVP** [comment]
> 
> 
> We can also do it in a backward compatible way. We can add a new keyword called `nchunks`, which is a better name for what this variable is actually doing, and raise a deprecation warning every time the old `chunksize` keyword is used, but it would have the same effect as `nchunks`. This way, we get a softer transition.

This sounds like a good solution. And is also very easy to implement.

**Comment by HDembinski** [comment]
Closed in master.
