### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by HenniOVP** [HDembinski/pyik#4]
Hi,
With Python 2 slowly phasing out of support (end of live: 2020) and Python 3 steadily moving forward, it would be great to get Python 3 compatibility for pyik.
During my work I found that most of the pyik-functions, that I use, already work with Python 3. And only once did I have the replace `xrange` with `range.` So I would expect porting to be relatively smooth.

Cheers,
Hendrik

**Comment by HDembinski** [comment]
implemented in master
