### ISSUE TITLE
2D and 3D histograms in ROOT-like style.

### ISSUE THREAD

**Issue by alasfar-lina** [HDembinski/pyik#7]
Expanding the Plot_hist() to include plotting 2d and 3d histograms in root style. 
Expanding plot Hist to add errors, like in ROOT (hist -> SetError(err))

**Comment by HDembinski** [comment]
`pyik.mplext` is a set of tools which are missing in matplotlib. We try to not implement functionality that can already be obtained with standard matplotlib commands. We don't want to write powerful new interfaces to matplotlib, rather only supply tools that are currently really missing.

`plot_hist` is strictly for 1d histograms. `matplotlib` provides tools to draw 2d histograms in 2d and 3d. Errors can be plotted with `pyplot.errorbar`. The classic skyline representation of a histogram is a good choice when either error bars are not relevant or too small to be important. When error bars are important, it is better to use `pyplot.errorbar` and not draw a skyline.
